package com.example.lvl1final.presentation

object Arguments {
    const val ARG_ALL_TYPE = "ALL"
    const val ARG_SERIES_TYPE = "TV_SERIES"
    const val ARG_FILM_TYPE = "FILM"
    const val ARG_FIRST_SELECTION = "FIRST_SELECTION"
    const val ARG_SECOND_SELECTION = "SECOND_SELECTION"
    const val ARG_IMAGE = "IMAGE"
    const val ARG_DESCRIPTION = "DESCRIPTION"
    const val TOP_250 = "TOP_250_BEST_FILMS"
    const val TOP_POPULAR = "TOP_100_POPULAR_FILMS"
    const val TOP_PREMIERES = "PREMIERES"
    const val TYPE = "TYPE"
    const val COLLECTION_NAME = "COLLECTION_NAME"
    const val ARG_SIMILAR_MOVIES = "SIMILAR_MOVIES"

    const val MOVIE_IMAGES_TYPE_STILL = "STILL"
    const val MOVIE_IMAGES_TYPE_SHOOTING = "SHOOTING"
    const val MOVIE_IMAGES_TYPE_POSTER = "POSTER"
    const val MOVIE_IMAGES_TYPE_FAN_ART = "FAN_ART"
    const val MOVIE_IMAGES_TYPE_PROMO = "PROMO"
    const val MOVIE_IMAGES_TYPE_CONCEPT = "CONCEPT"
    const val MOVIE_IMAGES_TYPE_WALLPAPER = "WALLPAPER"
    const val MOVIE_IMAGES_TYPE_COVER = "COVER"
    const val MOVIE_IMAGES_TYPE_SCREENSHOT = "SCREENSHOT"

    val movieImagesTypes = listOf(
        MOVIE_IMAGES_TYPE_STILL,
        MOVIE_IMAGES_TYPE_SHOOTING,
        MOVIE_IMAGES_TYPE_POSTER,
        MOVIE_IMAGES_TYPE_FAN_ART,
        MOVIE_IMAGES_TYPE_PROMO,
        MOVIE_IMAGES_TYPE_CONCEPT,
        MOVIE_IMAGES_TYPE_WALLPAPER,
        MOVIE_IMAGES_TYPE_COVER,
        MOVIE_IMAGES_TYPE_SCREENSHOT
    )

    const val MOVIE_STAFF_PROFESSION_WRITER = "WRITER"
    const val MOVIE_STAFF_PROFESSION_OPERATOR = "OPERATOR"
    const val MOVIE_STAFF_PROFESSION_EDITOR = "EDITOR"
    const val MOVIE_STAFF_PROFESSION_COMPOSER = "COMPOSER"
    const val MOVIE_STAFF_PROFESSION_PRODUCER_USSR = "PRODUCER_USSR"
    const val MOVIE_STAFF_PROFESSION_TRANSLATOR = "TRANSLATOR"
    const val MOVIE_STAFF_PROFESSION_DIRECTOR = "DIRECTOR"
    const val MOVIE_STAFF_PROFESSION_DESIGN = "DESIGN"
    const val MOVIE_STAFF_PROFESSION_PRODUCER = "PRODUCER"
    const val MOVIE_STAFF_PROFESSION_ACTOR = "ACTOR"
    const val MOVIE_STAFF_PROFESSION_VOICE_DIRECTOR = "VOICE_DIRECTOR"
    const val MOVIE_STAFF_PROFESSION_UNKNOWN = "UNKNOWN"
    const val MOVIE_STAFF_PROFESSION_HIMSELF = "HIMSELF"
    const val MOVIE_STAFF_PROFESSION_HERSELF = "HERSELF"
    const val MOVIE_STAFF_PROFESSION_HRONO_TITR_MALE = "HRONO_TITR_MALE"
    const val MOVIE_STAFF_PROFESSION_HRONO_TITR_FEMALE = "HRONO_TITR_FEMALE"
    const val MOVIE_STAFF_PROFESSION_VOICE_FEMALE = "VOICE_FEMALE"
    const val MOVIE_STAFF_PROFESSION_VOICE_MALE = "VOICE_MALE"

    const val ARG_KINOPOISK_ID = "KINOPOISK_ID"
    const val ARG_GALLERY_IMAGE_URL = "IMAGE_URL"
    const val ARG_MOVIE_LIST = "MOVIE_LIST"
    const val ARG_ACTOR_BEST_MOVIES = "ACTOR_BEST_MOVIES"
    const val ARG_ACTOR_FILMOGRAPHY = "ACTOR_FILMOGRAPHY"

    const val ARG_FEMALE = "FEMALE"

    const val COLLECTION_TYPE_FAVORITE = "COLLECTION_TYPE_FAVORITE"
    const val COLLECTION_TYPE_DELAYED = "COLLECTION_TYPE_DELAYED"
    const val COLLECTION_TYPE_USER_CUSTOM = "COLLECTION_TYPE_USER_CUSTOM"
    const val COLLECTION_TYPE_WATCHED = "COLLECTION_TYPE_WATCHED"
    const val COLLECTION_TYPE_INTERESTING = "COLLECTION_TYPE_INTERESTING"

    const val FAVORITE_COLLECTION_ID = 1
    const val DELAYED_COLLECTION_ID = 2

    const val WATCHED_COLLECTION = "WATCHED_COLLECTION"
    const val INTERESTING_COLLECTION = "INTERESTING_COLLECTION"

    const val SORT_BY_RATING_FILTER = "RATING"
    const val SORT_BY_NUM_VOTE_FILTER = "NUM_VOTE"
    const val SORT_BY_YEAR_FILTER = "YEAR"

    const val ALL_COUNTRY = ""
    const val ALL_GENRE = ""

    const val ARG_LIST_TYPE = "LIST_TYPE"
    const val ARG_COUNTRY_LIST = "COUNTRY_LIST"
    const val ARG_GENRE_LIST = "GENRE_LIST"

    const val MOVIE_CREW_TYPE_NAME = "MOVIE_CREW_TYPE_NAME"

}