package com.example.lvl1final.domain.models.movieimpl

import com.example.lvl1final.domain.models.movie.KinopoiskMovieInfo

data class KinopoiskMovieInfoImpl (
    override val completed: Boolean?,
    override val countries: List<CountryImpl>,
    override val coverUrl: String?,
    override val description: String?,
    override val editorAnnotation: String?,
    override val endYear: Int?,
    override val filmLength: Int?,
    override val genres: List<GenreImpl>,
    override val has3D: Boolean?,
    override val hasImax: Boolean?,
    override val imdbId: String?,
    override val isTicketsAvailable: Boolean,
    override val kinopoiskId: Int,
    override val lastSync: String,
    override val logoUrl: String?,
    override val nameEn: String?,
    override val nameOriginal: String?,
    override val nameRu: String?,
    override val posterUrl: String,
    override val posterUrlPreview: String,
    override  val productionStatus: String?,
    override val ratingAgeLimits: String?,
    override val ratingAwait: Double?,
    override val ratingAwaitCount: Int?,
    override val ratingFilmCritics: Double?,
    override val ratingFilmCriticsVoteCount: Int?,
    override  val ratingGoodReview: Double?,
    override val ratingGoodReviewVoteCount: Int?,
    override val ratingImdb: Double?,
    override val ratingImdbVoteCount: Int?,
    override val ratingKinopoisk: Double?,
    override val ratingKinopoiskVoteCount: Int?,
    override val ratingMpaa: String?,
    override val ratingRfCritics: Double?,
    override  val ratingRfCriticsVoteCount: Int?,
    override val reviewsCount: Int,
    override val serial: Boolean?,
    override val shortDescription: String?,
    override val shortFilm: Boolean?,
    override val slogan: String?,
    override val startYear: Int?,
    override val type: String,
    override val webUrl: String,
    override val year: Int?
) : KinopoiskMovieInfo